In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df.head(3)

area   price
0  2600  550000
1  3000  565000
2  3200  610000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

C:\Users\SUPRATIM\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [8]:
import pickle

In [9]:
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [12]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [14]:
mp.predict([[5000]])

C:\Users\SUPRATIM\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [16]:
#more object which on objects that carry large numpy arrays internally as is often the case (Joblib )

In [21]:
from sklearn.externals import joblib
joblib.dump(model, 'model_joblib')

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\SUPRATIM\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\externals\__init__.py)

In [22]:
mj = joblib.load('model_joblib')
mj.coef_

NameError: name 'joblib' is not defined